### PR TITLE
Add "atom_type" propertie to Tinker format

### PR DESCRIPTION
**Pull request by sguionni**

### CODE REVIEW

**Comment by sguionni** [comment]
I don't know how to write tests, where are located test data?

**Comment by Luthaf** [comment]
If you configure chemfiles locally with `cmake -DCHFL_BUILD_TESTS=ON .`, the files at https://github.com/chemfiles/tests-data are automatically downloaded. We already have a few tinker files for tests (https://github.com/chemfiles/tests-data/tree/master/tinker), so you would mainly have to add test code in [`tests/formats/tinker.cpp`](https://github.com/chemfiles/chemfiles/blob/93832d1f7c7bc38a6440394bfe506ddb4f54a887/tests/formats/tinker.cpp#L20)

Regarding the documentation, all properties are documented in [`doc/src/properties/atom.toml`](https://github.com/chemfiles/chemfiles/blob/93832d1f7c7bc38a6440394bfe506ddb4f54a887)/doc/src/properties/atom.toml, which is then used to generate [this documentation page](https://chemfiles.org/chemfiles/latest/properties.html).

**Comment by sguionni** [comment]
I'm finally adding changes, how can i locally run tests?
Thenn, I need to create another PR?

**Comment by Luthaf** [comment]
After configuring with `cmake -DCHFL_BUILD_TESTS=ON .` and building the code (make/ninja/...), you can run the tests with `ctest` or `make test`.

>  Then, I need to create another PR (close this one and make one PR with code/tests/doc)?

You can also add commits to this branch, it should work too. If you prefer to create a new PR, that's also fine!

**Comment by Luthaf** [comment]
I'll merge when CI passes 😃

**Pull request merged**
