### PR TITLE
fix(trajectory): do not allow reading frames in append mode

### LINKED ISSUE #272: Do not allow reading trajectories in append mode
It is currently [possible to read in append](https://github.com/chemfiles/chemfiles/blob/e13319b23ff86a5f949875dd5d66ccacf609b999/src/Trajectory.cpp#L137) mode.
IMHO this is not good:
- In C appending allows writing only (see [7.21.5.3  The `fopen` function](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf))
- When implementing writing/appending for some formats (I will hopefully have time to tackle XTC+TRR in a while) the underlying library (e.g. xdrfile) does not support reading while appending in most cases. So one would have to rewrite/do ugly workarounds to allow sthis anyways :(

Any thoughts on this?

Could do a PR that forbids this, it doesn't seem to break any tests :D

### PR DESCRIPTION
**Pull request by ezavod**
Fixes #272.

### CODE REVIEW

**Comment by Luthaf** [comment]
You will want to also update the documentation in Trajectory.hpp, and perhaps in the doc/ directory too.

**Comment by ezavod** [comment]
Sorry, good point, am not used to having such elaborate comments/documentation. There seem to be no occurrences in doc/

**Comment by Luthaf** [comment]
And this should be a CHANGELOG entry (sorry for not thinking about this earlier ...)

**Comment by ezavod** [comment]
Sure, I also forgot to add the TRR stuff the last time.

**Pull request merged**
