### PR TITLE
fix(README): replace outdated method in example

### PR DESCRIPTION
**Pull request by ezavod**
See #126. Not a big issue, but I'm just getting started and the first thing I tried didn't work.

### CODE REVIEW

**Comment by Luthaf** [comment]
Thank you very much for taking the time to do this!

**Comment by Luthaf** [comment]
And let us know if you find something hard to understand in the documentation, beginners feedback is very appreciated!

**Comment by ezavod** [comment]
@Luthaf Thanks for offering your help and the fast response. I'm mainly interested in the rust bindings. Just noticed that there are similar issues. I could do a PR there if your interested because I just got that example to work.

**Comment by Luthaf** [comment]
> I could do a PR there if your interested because I just got that example to work.

Please do!

**Pull request merged**
