### PR TITLE
Rewrite PDB secondary structure reading to use file order of residues

### PR DESCRIPTION
**Pull request by frodofine**
Fixes issue #342 by rewriting how secondary structures are read in PDB files. Instead of relying on a map with ordered residue information, this PR sets a 'flag' which contains the current residue secondary structure (as a string) and the final residue which has the given secondary structure. This, in effect, causes secondary structures to be read in the same order as the PDB.

### CODE REVIEW

**Comment by Luthaf** [comment]
I tried to parse the whole PDB archive with 0.9.3 and this, and this fixes all segfaults! 

Here are the previously segfaulting PDB id:

```
'2F16', '2FAK', '2FDP', '3NY8', '3NY9', '3NZJ', '3NZW', '3NZX', '3PDS', '3PI5',
'3PJS', '2B5T', '2B8L', '2B8V', '3DM6', '3DUY', '3DV1', '3DV5', '3DY3', '3DY4',
'6KJV', '6KK1', '6KK7', '6KP6', '6KPC', '6KQI', '6KUW', '6KUX', '6KUY', '6LI0',
'6LI2', '6LN2', '2QZL', '1TQ7', '1TQF', '1UCY', '5JTB', '5K2A', '5K2B', '5K2C',
'5K2D', '1MUE', '6A93', '6A94', '6AQF', '4ACU', '4ACX', '5EWX', '5VRA', '5WF5',
'5WF6', '5WIU', '5WIV', '3RZE', '3S7K', '3SHJ', '3SHR', '6GT3', '4FFH', '2HIZ',
'2HK2', '2HK3', '1Q6J', '1Q6M', '1BTH', '6PRZ', '6PS0', '6PS1', '6PS3', '6PS4',
'6PS5', '6PS6', '6PS7', '6PS8', '5YQZ', '1RD3', '1RP1', '1A4K', '1A7L', '5G3L',
'5GLI', '4YDV', '3D0S', '3D29', '5NDD', '5NDZ', '5NM2', '1YGP', '3EXO', '3F5H',
'3K5C', '3K5D', '3K5F', '3K5G', '4NC3', '4NTJ', '4AZY', '4B00', '4B05', '4B1C',
'4B1D', '4B1E', '4B1X', '4B72', '3GPJ', '3GPT', '3GPW', '5ZKP', '5ZKQ', '2FQ9',
'2FRA', '2FUD', '1IEA', '3KYR', '1AVG', '1AYE', '1BBR', '2ZCY', '2ZJH', '2ZJI',
'2ZJL', '2ZJM', '1SWG', '1TB6', '1TBQ', '1TBR', '2GPL', '1HTO', '1HTQ', '1IAO',
'1JMO', '1JOU', '1JPL', '1JR3', '1JUQ', '3GIS', '5D5A', '5D6L', '6OBA', '6OL9',
'6JZH', '1CJ0', '5UVI', '5VEW', '5VEX', '6IGK', '6IGL', '6INS', '6IQL', '6J20',
'6J21', '4MJO', '4N6H', '4N9N', '6FJ3', '3UFL', '3UQP', '6QFI', '6RZ6', '6RZ7',
'6RZ8', '6RZ9', '4LXA', '4LXK', '4LXM', '4LZ4', '4M00', '3LU9', '3W82', '3WFS',
'2PGQ', '2PH6', '2PH8', '2PUX', '2PV9', '1DLE', '5OLG', '5OLH', '5OLO', '5OLV',
'5OLZ', '5OM1', '5OM4', '2IQG', '2IRZ', '2IS0', '5TUD', '5TVN', '5U09', '2A1D',
'2E27', '6LW5', '6ME2', '6ME3', '6ME5', '6ME7', '6ME8', '6ME9', '6MH8', '2NTR',
'2OAH', '2OCV', '2ODY', '3AZ3', '3B9F', '3BDM', '3BEF', '3BEI', '5XJM', '3E47',
'3E6P', '3EDX', '3EML', '3ERR', '4XA3', '4XA6', '4XNV', '4XNW', '4IAQ', '4IAR',
'4IB4', '3QAK', '3QBH', '3QIN', '3QIO', '3QPM', '3QTE', '4CPB', '5UEN', '5UIG',
'5UIW', '5UNF', '4DJH', '4DY7', '3TDD', '6HLL', '6HLO', '6HLP', '1EF0', '2JX4',
'1M4H', '1M6D', '3MG0', '6DRX', '6DRY', '6DRZ', '6DS0', '6E59', '6E67', '4H6T',
'4HCQ', '5T04', '5WQC', '5WS3', '5X7D', '5X93', '5XEZ', '5XF1', '5IU4', '5IU7',
'5IU8', '5IUA', '5IUB', '4Z35', '4Z9G', '4ZJ8', '4ZJC', '1FL5', '1FL6', '6D32',
'6D35', '4ZPE', '4ZPF', '4ZPG', '4ZWJ', '3VR2', '3VR3', '3VR4', '3VR5', '3VR6',
'3VSF', '3VSZ', '3VT0', '3VT2', '3VW7', '3HK6', '3HKI', '3HYE', '3HYF', '3I25',
'4EIY', '4EJ4', '1XN2', '1XN3', '1VSN', '1VTO', '3OKJ', '3OSS', '2P4J', '2P83',
'2P8H', '1FWX', '1G65', '1GCJ', '4RKO', '4S0V', '6BQG', '6BQH', '6TPG', '6TPJ',
'6TPN', '3IQJ', '4PXZ', '4PY0', '4Q7R', '4Q7T', '4Q7U', '4QIM', '4QIN', '1Z8I',
'1Z8J'
```

I still would like to know if we have any guarantee on record order, I'll run a quick test for this.

**Comment by frodofine** [comment]
Glad there are no more segfaults! Don't have as much time to code with my new position - but I'll still try to contribute!

**Comment by Luthaf** [comment]
I checked half of the PDB archive before my script crashed, and none have HELIX or SHEET records after ATOM records. So even if this is not guaranteed by the standard as far as I understand, I think we can merge this!

**Comment by frodofine** [comment]
Great!

**Pull request merged**
