### PR TITLE
Do not use execptions when reading line by line

### PR DESCRIPTION
**Pull request by Luthaf**
This is a better fix for #203, completely removing the use of exceptions here.

### CODE REVIEW

**Comment by Luthaf** [comment]
> I'm a bit confused, is this a replacement for the other PR?

No, this PR is against master, and the other one against the release-0.8 branch. I prefer not changing the code too much in the 0.8 release, and using the less hacky way here, hence the two PR =)

**Comment by frodofine** [comment]
Understood!

Somewhat related question:

Do you have a release timeline for v0.9.0? I need a 'frozen' version for a DARPA-related project combining chemistry, computer science, and physics!

**Comment by Luthaf** [comment]
> Do you have a release timeline for v0.9.0? 

As soon as possible! I think #197/#150 is the only remaining thing to do before starting the release process =)

**Comment by frodofine** [comment]
Sounds great. I think #187 and #192 can weight for after v0.9.

**Pull request merged**
