### PR TITLE
1st implementation of Property struct and PBD format with ATOM/HETATM…

### PR DESCRIPTION
**Pull request by pgbarletta**
… markup

from https://github.com/chemfiles/chemfiles/issues/95

OK, I learned some C++ today. Had never seen tagged unions before (I didn't even know that was a thing). 
The code still needs some work, but at least is functional (tested it in my application and it worked).  I should also update  the `write` function of `PDB.cpp` to check if the `Atom` object has `is_hetatm` set.

1. Didn't know where to put the new `Property` struct, so I chose `types.hpp`.
2. I'm using the base `Error()` function. 
3. Couldn't make it work with `std::string` and had to go with `char`. It should be possible though, since C+11 to use strings inside tagged unions, declaring constructors and destructors.
4. Couldn't
5. It seems that my `clang-format` package changed your code, I thought you used that package too. Once I'm done with this code I'll edit the original code from VIM, to avoid formatting changes.
6. Had to initialize a temporary variable `  struct Property tmp {is_hetatm};` to make it work. List initialization was the only way to avoid: `error: cannot convert ‘bool’ to ‘chemfiles::Property::<anonymous enum>`. Same thing would happen if either `kind_ enum` or the anonymous `union` were private, so I had to go with `Struct`

### CODE REVIEW

**Comment by Luthaf** [comment]
This looks nice, thanks !

> It seems that my clang-format package changed your code, I thought you used that package too. Once I'm done with this code I'll edit the original code from VIM, to avoid formatting changes.

This repository used to have a `.clang-format` file, but I removed it in https://github.com/chemfiles/chemfiles/commit/cb808effcd89081c5b4da4a41e55e7833699b764 because I was not using it. But maybe it is time to bring it back ^^

Maybe you can use the previous .clang-format file locally to reformat the code ? Currently the diff is very hard to read.

> I'm using the base Error() function.

You can add a new `PropertyError` class for this.

> Didn't know where to put the new Property struct, so I chose types.hpp.

You can start a new file, the code is complex enough for this. 

> Had to initialize a temporary variable struct Property tmp = {is_hetatm}; to make it work. List initialization was the only way to avoid: error: cannot convert ‘bool’ to ‘chemfiles::Property::<anonymous enum>

You should not need to do that, I'll give it a more in-depth look after you reformat the code =)

FYI I also started working on this in these commits (b78ee3958264a2c792fb85b86b1c331f84c6d90d, 0733b8ed39b1cd2973684d0ab20d75076521a46b, b9854efb53135f844ca3a5ec6a442e02c8aa3260). Maybe you can draw some inspiration from it, concerning the use of std::string for example. I am fine with using your code instead!

**Comment by pgbarletta** [comment]
Oh, that pretty much solves it.
Correct me if I'm wrong, but with those commits, all is left for me to do is to modify the PDB format. Right?

**Comment by Luthaf** [comment]
>  Correct me if I'm wrong, but with those commits, all is left for me to do is to modify the PDB format. Right?

This, and adding a `CHFL_PROPERTY` struct on the C API side (I have a WIP for this locally 😄).

**Comment by pgbarletta** [comment]
Closed and replaced by https://github.com/chemfiles/chemfiles/pull/97

**Pull request closed without merging**
