### PR TITLE
Switch to BSD license

### LINKED ISSUE #48: Relicense the code under BSD?
I do not know if this is worth it, the BSD does not have that much advantages compared to MPL. Opening this to discuss, if you have an opinion or a requirement concerning Chemfiles licensing, please tell us!

### PR DESCRIPTION
**Pull request by Luthaf**
Fix #48.

This changes the license of the code to BSD, which only requires attribution of copyright. I believe that a more permissive license can help adoption of the code.

@pgbarletta and @pelsa, you contributed code to this repository under the previous license. Do you agree to distribute your contributions under the BSD license? If so, please leave a comment here!

### CODE REVIEW

**Comment by pgbarletta** [comment]
Fine by me!
By the way, this reminds me of asking you, are you planning to publish these libraries in a peer-review journal any time soon? I'm starting to write the manuals for my software next week, and should be submitting my project in ~2 months. If chemfiles had an original publication, it would be the first paper to acknowledge.

**Comment by Luthaf** [comment]
>  By the way, this reminds me of asking you, are you planning to publish these libraries in a peer-review journal any time soon? I'm starting to write the manuals for my software next week, and should be submitting my project in ~2 months. If chemfiles had an original publication, it would be the first paper to acknowledge.

Great new! And thanks for thinking to cite chemfiles!

I would like to submit this to a peer reviewed journal someday, but I wont get it in 2 months. But I could submit this to [JOSS](http://joss.theoj.org/), and get a citable DOI. I'll try to do this quickly, so that you can have a DOI to cite. Or if you are using a specific release of chemfiles, I could generate a Zenodo DOI corresponding to this.

**Comment by Luthaf** [comment]
BTW, is your project accessible somewhere? I'd like to add a section 'Projects using chemfiles' in the README, I can add a link to your work there!

**Comment by pgbarletta** [comment]
> BTW, is your project accessible somewhere?

Currently, no, I decided to keep it private until its finished. The thing is, my first lines of C++ code were written in this project, so it's taking me a lot of time to write something a more experienced programmer would finish in a matter of months. Moreover, software programming has little to do with my original thesis topic (protein non-equilibrium dynamics) so I knew I couldn't devote much time to it while at the same time, comparable software is written by teams of experienced programmers. 
I think (hope) my software does some things right and has some useful tricks. I'd like to get a publication and some cites before someone else takes these ideas and use them to make a better software. Or maybe I'm just delusional and nobody will care for it.

So, as soon as its ready and prior to any publication attempt, I'll upload it to github and let you know.

**Comment by Luthaf** [comment]
> So, as soon as its ready and prior to any publication attempt, I'll upload it to github and let you know.

Great, thanks!

**Comment by Luthaf** [comment]
Pinging @pelsa here, do you agree with this?

Also pinging @lscalfi, as #77 will land soon! Do you agree with releasing your changes under the BSD license?

**Comment by lscalfi** [comment]
Yes of course!

**Comment by pelsa** [comment]
Of course I agree !

**Comment by Luthaf** [comment]
Thank you!

**Comment by Luthaf** [comment]
@pgbarletta I create a DOI for chemfile that you can cite: https://doi.org/10.5281/zenodo.800663.

**Pull request merged**
