### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Luthaf**
This adds a new part in the README containing a list of  'other codes using chemfiles'

@frodofine does the description of lemon sounds good, or do you prefer something else? Also, are you using chemfiles in another project?

@ezavod and @pgbarletta, are you using chemfiles in publicly available projects?

### CODE REVIEW

**Comment by frodofine** [comment]
Looks good to me!

I am using it in other projects, but they are not public (yet). I'll add them here when they do become public.

**Comment by pgbarletta** [comment]
I added mine.

**Comment by ezavod** [comment]
I have nothing to add yet. I am using chemfiles mainly in quick and dirty analysis scripts.

**Comment by Luthaf** [comment]
Thanks everyone!

**Pull request merged**
